title: An Muinteoir Mata
description: Free maths help for Irish secondary school students
theme: minima
baseurl: "/anmuinteoirmata"  # <--- Empty for user site
url: "https://anmuinteoirmata.github.io"
